### ISSUE TITLE
undefined method `encode_www_form' for URI:Module

### ISSUE THREAD

**Issue by igorsobreira** [igorsobreira/fms-admin-api#17]
Ruby 1.8.7

**Comment by igorsobreira** [comment]
Ruby 1.8 is not supported

**Comment by RashmiRatnaparkhi** [comment]
Any workaround solution to make it work with Ruby 1.8.7 ?

**Comment by igorsobreira** [comment]
I don't know any workaround @RashmiRatnaparkhi, I wasn't working with 1.8.7. Let me know if you find any, any contribution to work with other versions of ruby are very welcome too.

**Comment by RashmiRatnaparkhi** [comment]
Well I got this error while installing curb -v 0.8.5. I downgraded the version to Curb -v 0.7.18 to prevent this error but now issue is "Undefined method curl.post "
